vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,org.raksti.web

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  mail:
    host: vh3.makonix.com
    port: 587
    username: no-reply@raksti.org
    password: gXiucM12yVVH
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true

  mustache:
    check-template-location: false
  datasource:
    password: adminsuper
    url: jdbc:postgresql://localhost:5432/raksti
    username: postgres
  security:
    oauth2:
    user:
      password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show_sql: true
logging:
  level:
    org:
      atmosphere: warn


