vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,com.example.application

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  social:
    facebook:
      appId: 386571800254339
      appSecret: e3757043012f50c32297a2ab59b4871c
  mail:
    host: smtp.gmail.com
    port: 587
    username: torino1337@gmail.com
    password: zqgrwcuavprpshyi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true

  mustache:
    check-template-location: false
  datasource:
    password: adminsuper
    url: jdbc:postgresql://localhost:5432/raksti
    username: postgres
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 386571800254339
            clientSecret: e3757043012f50c32297a2ab59b4871c
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            resource:
              userInfoUri: https://graph.facebook.com/me
    user:
      password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        format_sql: true
    show_sql: true
logging:
  level:
    org:
      atmosphere: warn


